// Generates the tables in src/tailwind from Tailwind CSS:
//
//   deno run -A scripts/generate_tailwind_tables.ts
//
// - tables.rs has the order of Tailwind's utilities and variants
// - sort_tests.txt has class lists sorted by Tailwind, which the tests in
//   src/tailwind check the Rust code sorts the same way
// - sort_tests_project.txt has the same for a project that customizes Tailwind
//
// Bump the version in the import below to update to a newer Tailwind.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { __unstable__loadDesignSystem } from "npm:tailwindcss@4.3.3";

const tailwindVersion = "4.3.3";
const require = createRequire(import.meta.url);

interface SortKey {
  /** Indexes of the CSS properties a utility sets in Tailwind's property order. */
  order: number[];
  /** Number of declarations, where utilities with more go first. */
  count: number;
}

/** Prefixes of the theme variables along with a value to use for a theme variable that has it. */
const themeNamespaces: [string, string][] = [
  ["--color-", "#000"],
  ["--text-", "1rem"],
  ["--font-", "serif"],
  ["--font-weight-", "700"],
  ["--tracking-", "1em"],
  ["--leading-", "1"],
  ["--spacing-", "1rem"],
  ["--radius-", "1rem"],
  ["--shadow-", "0 0 #000"],
  ["--inset-shadow-", "inset 0 0 #000"],
  ["--drop-shadow-", "0 0 #000"],
  ["--text-shadow-", "0 0 #000"],
  ["--blur-", "1px"],
  ["--perspective-", "1px"],
  ["--aspect-", "1 / 1"],
  ["--ease-", "linear"],
  ["--animate-", "spin 1s linear"],
  ["--container-", "1rem"],
  ["--breakpoint-", "1rem"],
];
/** The customizations of the project that sort_tests_project.txt is for, which the Rust test has too. */
const projectPrefix = "tw";
const projectCss = `
@theme {
  --breakpoint-3xl: 120rem;
  --breakpoint-xs: 30rem;
  --container-8xl: 90rem;
  --color-brand: #f00;
  --color-brand-dark: #900;
  --text-huge: 4rem;
  --font-display: "Display";
  --font-weight-heavy: 950;
  --shadow-glow: 0 0 8px #fff;
  --radius-blob: 3rem;
  --spacing-gutter: 1.5rem;
  --ease-snappy: cubic-bezier(0.2, 0, 0, 1);
}
@custom-variant theme-midnight (&:where([data-theme="midnight"] *));
@custom-variant hocus (&:hover, &:focus);
@utility btn {
  display: inline-flex;
  padding: 1rem;
}
@utility tab-* {
  tab-size: --value(integer);
}
`;

const design = await loadDesign("");
const sortKeys = new Map<string, SortKey | undefined>();
const properties = new Set<string>();
const utilities = getUtilities();
const propertyIndexes = getPropertyIndexes();
const themePositions = await getThemeKeys();
const allSortKeys = getAllSortKeys();
const variants = getVariants();

writeFileSync(new URL("../src/tailwind/tables.rs", import.meta.url), getTablesText());
writeFileSync(new URL("../src/tailwind/sort_tests.txt", import.meta.url), getSortTestsText());
writeFileSync(new URL("../src/tailwind/sort_tests_project.txt", import.meta.url), await getProjectSortTestsText());

// deno-lint-ignore no-explicit-any
function loadDesign(css: string, importOptions = ""): Promise<any> {
  return __unstable__loadDesignSystem(`@import "tailwindcss"${importOptions};\n${css}`, {
    base: ".",
    loadStylesheet: (id: string, base: string) => {
      const path = require.resolve(id === "tailwindcss" ? "tailwindcss/index.css" : id);
      return Promise.resolve({ path, base, content: readFileSync(path, "utf8") });
    },
  });
}

function getTablesText() {
  const exact = Array.from(utilities.exact.keys()).sort(compareText);
  const roots = Array.from(utilities.roots.entries()).sort((a, b) => compareText(a[0], b[0]));
  const position = (className: string) => getPosition(getSortKey(className)!);
  let text = `//! Order of the utilities and variants in Tailwind CSS ${tailwindVersion}.\n`;
  text += "//!\n";
  text += "//! Generated by scripts/generate_tailwind_tables.ts. Do not edit this file.\n\n";
  text += "/// What Tailwind orders utilities by, which is the indexes of the CSS properties a utility\n";
  text += "/// sets in Tailwind's property order along with how many declarations it has.\n";
  text += "///\n";
  text += "/// This has the ones of the utilities in the tables below in the order Tailwind sorts them.\n";
  text += "/// The position of a utility is the index of its entry doubled plus one, which leaves the\n";
  text += "/// even numbers for utilities that sort between two entries.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const SORT_KEYS: &[(&[u16], u16)] = &[\n${
    allSortKeys.map(key => `  (&[${key.order.join(", ")}], ${key.count}),\n`).join("")
  }];\n\n`;
  text += "/// Utilities that are matched on their entire text along with their position.\n";
  text += "///\n";
  text += "/// This has the utilities that don't have a value (ex. `flex`) and the ones whose position\n";
  text += "/// differs from their root's default one (ex. `text-sm`, which is not a color).\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const UTILITIES: &[(&str, u16)] = &[\n${
    exact.map(name => `  (${quote(name)}, ${position(name)}),\n`).join("")
  }];\n\n`;
  text += "/// Roots of the utilities that are followed by a value (ex. `text` in `text-red-500`) along with\n";
  text += "/// the position for most of their values, for an arbitrary length, and for an arbitrary color.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const UTILITY_ROOTS: &[(&str, u16, u16, u16)] = &[\n${
    roots.map(([name, root]) =>
      `  (${quote(name)}, ${position(root.default)}, ${position(root.arbitraryLength)}, ${
        position(root.arbitraryColor)
      }),\n`
    ).join("")
  }];\n\n`;
  text += "/// Roots of the utilities whose position is not their default one when their value is the name\n";
  text += "/// of a theme variable with a certain prefix (ex. `text-huge` when there's a `--text-huge`).\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const UTILITY_THEME_POSITIONS: &[(&str, &str, u16)] = &[\n${
    themePositions.map(([root, namespace, key]) => `  (${quote(root)}, ${quote(namespace)}, ${getPosition(key)}),\n`)
      .join("")
  }];\n\n`;
  text += "/// CSS properties along with their index in Tailwind's property order.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const PROPERTIES: &[(&str, u16)] = &[\n${
    propertyIndexes.map(([name, index]) => `  (${quote(name)}, ${index}),\n`).join("")
  }];\n\n`;
  text += "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n";
  text += "pub enum VariantKind {\n";
  text += "  /// Doesn't have a value (ex. `hover`).\n";
  text += "  Static,\n";
  text += "  /// May be followed by a value (ex. `data` in `data-active`).\n";
  text += "  Functional,\n";
  text += "  /// Is followed by another variant (ex. `group` in `group-hover`).\n";
  text += "  Compound,\n";
  text += "}\n\n";
  text += "/// How variants that have the same position are ordered.\n";
  text += "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n";
  text += "pub enum VariantValueOrder {\n";
  text += "  /// By their root then value.\n";
  text += "  None,\n";
  text += "  /// From the smallest value to the largest (ex. the width of the breakpoint in `min-md`).\n";
  text += "  Ascending,\n";
  text += "  /// From the largest value to the smallest (ex. the width of the breakpoint in `max-md`).\n";
  text += "  Descending,\n";
  text += "}\n\n";
  text += "/// Roots of the variants along with their position.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const VARIANTS: &[(&str, VariantKind, u16, VariantValueOrder)] = &[\n${
    variants.roots.map(v =>
      `  (${quote(v.root)}, VariantKind::${v.kind}, ${v.order}, VariantValueOrder::${v.valueOrder}),\n`
    ).join("")
  }];\n\n`;
  text += "/// Variants that are ordered by their value along with that value.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const VARIANT_VALUES: &[(&str, &str)] = &[\n${
    variants.values.map(([name, value]) => `  (${quote(name)}, ${quote(value)}),\n`).join("")
  }];\n`;
  return text;
}

function getUtilities() {
  const staticNames = new Set<string>(design.utilities.keys("static"));
  const functionalRoots = new Set<string>(design.utilities.keys("functional"));
  const classNames: string[] = design.getClassList()
    .map(([name]: [string]) => name)
    // negative utilities have the position of the positive one
    .filter((name: string) => !name.startsWith("-") && getSortKey(name) != null);
  const classNamesByRoot = new Map<string, string[]>();
  const exact = new Set<string>();
  for (const name of classNames) {
    const root = staticNames.has(name) ? undefined : findRoot(name);
    if (root == null) {
      exact.add(name);
    } else {
      classNamesByRoot.set(root, [...classNamesByRoot.get(root) ?? [], name]);
    }
  }

  const roots = new Map<string, { default: string; arbitraryLength: string; arbitraryColor: string }>();
  for (const root of functionalRoots) {
    // the position of a value that's not known is the most common one of the known values
    const names = classNamesByRoot.get(root) ?? [];
    const counts = new Map<string, { name: string; count: number }>();
    for (const name of names) {
      const key = JSON.stringify(getSortKey(name));
      const entry = counts.get(key) ?? { name, count: 0 };
      entry.count++;
      counts.set(key, entry);
    }
    const arbitraryLength = [`${root}-[1px]`].find(name => getSortKey(name) != null);
    const arbitraryColor = [`${root}-[#000]`].find(name => getSortKey(name) != null);
    const defaultName = Array.from(counts.values()).sort((a, b) => b.count - a.count)[0]?.name
      ?? [arbitraryLength, arbitraryColor, `${root}-[initial]`, `${root}-1`].find(name =>
        name != null && getSortKey(name) != null
      );
    if (defaultName == null) {
      continue;
    }
    roots.set(root, {
      default: defaultName,
      arbitraryLength: arbitraryLength ?? defaultName,
      arbitraryColor: arbitraryColor ?? defaultName,
    });
    const defaultKey = JSON.stringify(getSortKey(defaultName));
    for (const name of names) {
      if (JSON.stringify(getSortKey(name)) !== defaultKey) {
        exact.add(name);
      }
    }
  }
  for (const [root, names] of classNamesByRoot) {
    if (!roots.has(root)) {
      names.forEach(name => exact.add(name));
    }
  }
  return { exact, roots };

  function findRoot(name: string) {
    if (functionalRoots.has(name)) {
      // has no value (ex. `border`), so needs to be matched on its entire text
      return undefined;
    }
    for (let index = name.lastIndexOf("-"); index > 0; index = name.lastIndexOf("-", index - 1)) {
      if (functionalRoots.has(name.substring(0, index))) {
        return name.substring(0, index);
      }
    }
    return undefined;
  }
}

function getPropertyIndexes() {
  const result: [string, number][] = [];
  for (const property of Array.from(properties).sort(compareText)) {
    const key = getSortKey(`[${property}:initial]`);
    if (key != null && key.order.length === 1) {
      result.push([property, key.order[0]]);
    }
  }
  return result;
}

/**
 * Gets the sort keys of the utilities whose position depends on the theme
 * variable their value is for, by adding a theme variable for each prefix.
 */
async function getThemeKeys() {
  const name = (namespace: string) => `probe${namespace.replaceAll("-", "")}`;
  const probeDesign = await loadDesign(
    `@theme {\n${themeNamespaces.map(([namespace, value]) => `${namespace}${name(namespace)}: ${value};\n`).join("")}}`,
  );
  const result: [string, string, SortKey][] = [];
  for (const [root, { default: defaultName }] of utilities.roots) {
    for (const [namespace] of themeNamespaces) {
      const key = getSortKey(`${root}-${name(namespace)}`, probeDesign);
      if (key != null && compareSortKeys(key, getSortKey(defaultName)!) !== 0) {
        result.push([root, namespace, key]);
      }
    }
  }
  return result.sort((a, b) => compareText(a[0], b[0]) || compareText(a[1], b[1]));
}

/** Gets the distinct sort keys of everything in the tables in the order Tailwind sorts them. */
function getAllSortKeys() {
  const keys = [
    ...utilities.exact.keys(),
    ...Array.from(utilities.roots.values()).flatMap(root => [root.default, root.arbitraryLength, root.arbitraryColor]),
  ].map(className => getSortKey(className)!).concat(themePositions.map(([, , key]) => key));
  keys.sort(compareSortKeys);
  return keys.filter((key, index) => index === 0 || compareSortKeys(keys[index - 1], key) !== 0);
}

function getPosition(key: SortKey) {
  const index = allSortKeys.findIndex(other => compareSortKeys(key, other) === 0);
  if (index === -1) {
    throw new Error(`Expected to find the sort key ${JSON.stringify(key)}.`);
  }
  return index * 2 + 1;
}

// deno-lint-ignore no-explicit-any
function getSortKey(className: string, designSystem: any = design): SortKey | undefined {
  const cacheKey = designSystem === design ? className : undefined;
  if (cacheKey != null && sortKeys.has(cacheKey)) {
    return sortKeys.get(cacheKey);
  }
  let result: SortKey | undefined;
  for (const candidate of designSystem.parseCandidate(className)) {
    for (const { node, propertySort } of designSystem.compileAstNodes(candidate)) {
      collectProperties(node);
      if (result == null || compareSortKeys(propertySort, result) < 0) {
        result = propertySort;
      }
    }
  }
  if (cacheKey != null) {
    sortKeys.set(cacheKey, result);
  }
  return result;
}

// deno-lint-ignore no-explicit-any
function collectProperties(node: any) {
  if (node.kind === "declaration") {
    if (!node.property.startsWith("--")) {
      properties.add(node.property);
    }
  } else {
    node.nodes?.forEach(collectProperties);
  }
}

/** Compares the same way as the sort in Tailwind's `compileCandidates`. */
function compareSortKeys(a: SortKey, b: SortKey) {
  let offset = 0;
  while (offset < a.order.length && offset < b.order.length && a.order[offset] === b.order[offset]) {
    offset++;
  }
  if (offset === a.order.length && offset === b.order.length) {
    return b.count - a.count;
  }
  return ((a.order[offset] ?? Infinity) - (b.order[offset] ?? Infinity)) || (b.count - a.count);
}

function getVariants() {
  const kinds: Record<string, string> = { static: "Static", functional: "Functional", compound: "Compound" };
  const roots = Array.from<[string, { kind: string; order: number }]>(design.variants.variants.entries())
    .map(([root, { kind, order }]) => ({
      root,
      kind: kinds[kind],
      order,
      // variants that share a position are ordered by their value (ex. the width of a breakpoint)
      valueOrder: !design.variants.compareFns.has(order)
        ? "None"
        : root === "max" || root === "@max"
        ? "Descending"
        : "Ascending",
    }))
    .sort((a, b) => compareText(a.root, b.root));
  const values: [string, string][] = [];
  const valuesByRoot = new Map<string, string[]>(
    design.getVariants().map((v: { name: string; values: string[] }) => [v.name, v.values]),
  );
  for (const { root, kind } of roots.filter(v => v.valueOrder !== "None")) {
    const themeKey = root.startsWith("@") ? "--container" : "--breakpoint";
    if (kind === "Static") {
      values.push([root, design.theme.resolveValue(root, [themeKey])]);
    }
    for (const value of valuesByRoot.get(root) ?? []) {
      values.push([root === "@" ? `@${value}` : `${root}-${value}`, design.theme.resolveValue(value, [themeKey])]);
    }
  }
  if (values.some(([, value]) => value == null)) {
    throw new Error("Expected every breakpoint to have a value.");
  }
  // ensure the directions above are right
  for (
    const [smaller, larger, expected] of [
      ["sm", "min-md", -1],
      ["max-sm", "max-md", 1],
      ["@sm", "@min-md", -1],
      ["@max-sm", "@max-md", 1],
    ] as const
  ) {
    if (Math.sign(design.variants.compare(design.parseVariant(smaller), design.parseVariant(larger))) !== expected) {
      throw new Error(`Unexpected order of ${smaller} and ${larger}.`);
    }
  }
  values.sort((a, b) => compareText(a[0], b[0]));
  return { roots, values };
}

function getSortTestsText() {
  const extraVariantNames = [
    ...["min-[400px]", "max-[600px]", "@[300px]", "@min-[20rem]", "@max-[40rem]"],
    ...["min-[30.5rem]", "max-[calc(100%-1rem)]", "@sm/sidebar"],
  ];
  const extraClassNames = [
    ...["text-[14px]", "text-[#bada55]", "bg-[#bada55]", "bg-[url(/img.png)]", "w-[32rem]", "p-[5px]"],
    ...["border-[3px]", "border-[#fff]", "[color:red]", "[mask-type:alpha]", "[--my-var:1px]", "m-[-2px]"],
    ...["grid-cols-[1fr_2fr]", "content-['hello']", "bg-red-500/50", "text-sm/6", "text-red-500/[0.5]"],
    ...["border-blue-300/25", "w-5/7", "-mt-[3px]", "text-(--my-color)", "text-(length:--my-size)"],
    ...["!p-4", "p-4!", "!flex", "text-red-500!", "foo", "bar", "unknown-class", "unknown:flex"],
  ];
  return createSortTestsText(design, 1000, 0.1, extraVariantNames, extraClassNames);
}

async function getProjectSortTestsText() {
  const projectDesign = await loadDesign(projectCss, ` prefix(${projectPrefix})`);
  const extraVariantNames = [
    ...["3xl", "xs", "min-3xl", "max-3xl", "max-xs", "@8xl", "@min-8xl", "@max-8xl"],
    ...["theme-midnight", "hocus", "group-hocus", "not-theme-midnight"],
  ];
  const extraClassNames = [
    ...["text-brand", "text-huge", "text-brand-dark", "bg-brand", "border-brand", "font-display", "font-heavy"],
    ...["shadow-glow", "shadow-brand", "rounded-blob", "p-gutter", "mx-gutter", "ease-snappy", "btn", "tab-4"],
    ...["tab-8", "ring-brand", "outline-brand", "decoration-brand", "stroke-brand", "max-w-8xl", "w-3xl"],
    ...["foo", "unknown-class"],
  ];
  const text = createSortTestsText(projectDesign, 500, 0.5, extraVariantNames, extraClassNames);
  const description = `# It's for a project that has the prefix \`${projectPrefix}\` and customizes Tailwind with:\n#${
    projectCss.trimEnd().replaceAll("\n", "\n# ")
  }\n#\n`;
  return text.replace("#\n", description);
}

function createSortTestsText(
  // deno-lint-ignore no-explicit-any
  designSystem: any,
  count: number,
  extraProbability: number,
  extraVariantNames: string[],
  extraClassNames: string[],
) {
  const random = createRandom(1);
  const pick = <T>(items: T[]) => items[Math.floor(random() * items.length)];
  const prefix = designSystem.theme.prefix == null ? "" : `${designSystem.theme.prefix}:`;
  // group the class names so that the many classes for colors don't crowd out the rest
  const classNameGroups = Array.from(
    Map.groupBy(
      design.getClassList().map(([name]: [string]) => name).filter((name: string) => getSortKey(name) != null),
      (name: string) => name.replace(/^-/, "").split("-")[0],
    ).values(),
  ) as string[][];
  const variantNames = [
    ...variants.roots.filter(v => v.kind === "Static").map(v => v.root),
    ...variants.values.map(([name]) => name),
    ...[
      "group-hover",
      "group-focus",
      "peer-checked",
      "peer-hover",
      "not-hover",
      "not-first",
      "has-checked",
      "in-focus",
    ],
    ...["group-hover/item", "peer-checked/name", "group-data-open", "not-data-active"],
    ...["aria-checked", "aria-busy", "data-active", "data-open", "data-[state=open]", "aria-[sort=ascending]"],
    ...["nth-3", "nth-last-2", "supports-grid", "supports-[display:grid]", "has-[img]"],
    ...["[&>*]", "[&:nth-child(3)]", "[@media(width>=600px)]"],
  ];
  const sizes = [2, 2, 3, 3, 4, 5, 6, 8, 12];
  let text = `# Class lists and how Tailwind CSS ${tailwindVersion} sorts them, separated by \`=>\`.\n`;
  text += "#\n";
  text += "# Generated by scripts/generate_tailwind_tables.ts. Do not edit this file.\n";
  for (let i = 0; i < count; i++) {
    const classes = Array.from({ length: pick(sizes) }, () => {
      const className = random() < extraProbability ? pick(extraClassNames) : pick(pick(classNameGroups));
      const variantCount = pick([0, 0, 0, 1, 1, 2, 3]);
      const classVariantNames = Array.from(
        { length: variantCount },
        () => pick(random() < extraProbability ? extraVariantNames : variantNames),
      );
      return prefix + [...classVariantNames, className].join(":");
    });
    text += `${classes.join(" ")} => ${sortClasses(designSystem, classes).join(" ")}\n`;
  }
  return text;
}

/** Sorts the same way as prettier-plugin-tailwindcss. */
// deno-lint-ignore no-explicit-any
function sortClasses(designSystem: any, classes: string[]) {
  const ordered: [string, bigint | null][] = designSystem.getClassOrder(classes);
  ordered.sort(([, a], [, b]) => {
    if (a === b) return 0;
    if (a === null) return -1;
    if (b === null) return 1;
    return a < b ? -1 : 1;
  });
  const seen = new Set<string>();
  return ordered.filter(([name, order]) => {
    if (seen.has(name)) return false;
    if (order !== null) seen.add(name);
    return true;
  }).map(([name]) => name);
}

/** Creates a seeded random number generator so that the output is reproducible. */
function createRandom(seed: number) {
  return () => {
    seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Compares by UTF-8 bytes like Rust does so that the tables can be binary searched. */
function compareText(a: string, b: string) {
  const encoder = new TextEncoder();
  const aBytes = encoder.encode(a);
  const bBytes = encoder.encode(b);
  for (let i = 0; i < Math.min(aBytes.length, bBytes.length); i++) {
    if (aBytes[i] !== bBytes[i]) {
      return aBytes[i] - bBytes[i];
    }
  }
  return aBytes.length - bBytes.length;
}

function quote(text: string) {
  return JSON.stringify(text);
}
