// Generates the tables in src/tailwind from Tailwind CSS:
//
//   deno run -A scripts/generate_tailwind_tables.ts
//
// - tables.rs has the order of Tailwind's utilities and variants
// - sort_tests.txt has class lists sorted by Tailwind, which the tests in
//   src/tailwind check the Rust code sorts the same way
//
// Bump the version in the import below to update to a newer Tailwind.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { __unstable__loadDesignSystem } from "npm:tailwindcss@4.3.3";

const tailwindVersion = "4.3.3";
const require = createRequire(import.meta.url);
// deno-lint-ignore no-explicit-any
const design: any = await __unstable__loadDesignSystem(`@import "tailwindcss";`, {
  base: ".",
  loadStylesheet: (id: string, base: string) => {
    const path = require.resolve(id === "tailwindcss" ? "tailwindcss/index.css" : id);
    return Promise.resolve({ path, base, content: readFileSync(path, "utf8") });
  },
});

interface SortKey {
  /** Indexes of the CSS properties a utility sets in Tailwind's property order. */
  order: number[];
  /** Number of declarations, where utilities with more go first. */
  count: number;
}

const sortKeys = new Map<string, SortKey>();
const properties = new Set<string>();
const utilities = getUtilities();
const propertyClassNames = new Map(Array.from(properties).sort().map(property => [property, `[${property}:initial]`]));
const unknownPropertyClassName = "[--unknown:initial]";
const ranks = getRanks([
  ...utilities.exact.keys(),
  ...Array.from(utilities.roots.values()).flatMap(root => [root.default, root.arbitraryLength, root.arbitraryColor]),
  ...propertyClassNames.values(),
  unknownPropertyClassName,
]);
const variants = getVariants();

writeFileSync(new URL("../src/tailwind/tables.rs", import.meta.url), getTablesText());
writeFileSync(new URL("../src/tailwind/sort_tests.txt", import.meta.url), getSortTestsText());

function getTablesText() {
  const exact = Array.from(utilities.exact.keys()).sort(compareText);
  const roots = Array.from(utilities.roots.entries()).sort((a, b) => compareText(a[0], b[0]));
  let text = `//! Order of the utilities and variants in Tailwind CSS ${tailwindVersion}.\n`;
  text += "//!\n";
  text += "//! Generated by scripts/generate_tailwind_tables.ts. Do not edit this file.\n\n";
  text += "/// Utilities that are matched on their entire text along with their position.\n";
  text += "///\n";
  text += "/// This has the utilities that don't have a value (ex. `flex`) and the ones whose position\n";
  text += "/// differs from their root's default one (ex. `text-sm`, which is not a color).\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const UTILITIES: &[(&str, u16)] = &[\n${
    exact.map(name => `  (${quote(name)}, ${ranks.get(name)}),\n`).join("")
  }];\n\n`;
  text += "/// Roots of the utilities that are followed by a value (ex. `text` in `text-red-500`) along with\n";
  text += "/// the position for most of their values, for an arbitrary length, and for an arbitrary color.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const UTILITY_ROOTS: &[(&str, u16, u16, u16)] = &[\n${
    roots.map(([name, root]) =>
      `  (${quote(name)}, ${ranks.get(root.default)}, ${ranks.get(root.arbitraryLength)}, ${
        ranks.get(root.arbitraryColor)
      }),\n`
    ).join("")
  }];\n\n`;
  text += "/// CSS properties along with the position of a utility that only sets that property (ex. `[color:red]`).\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const PROPERTIES: &[(&str, u16)] = &[\n${
    Array.from(propertyClassNames).map(([name, className]) => `  (${quote(name)}, ${ranks.get(className)}),\n`).join("")
  }];\n\n`;
  text += "/// Position of a utility that sets a CSS property that's not in `PROPERTIES`.\n";
  text += `pub const UNKNOWN_PROPERTY_POSITION: u16 = ${ranks.get(unknownPropertyClassName)};\n\n`;
  text += "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n";
  text += "pub enum VariantKind {\n";
  text += "  /// Doesn't have a value (ex. `hover`).\n";
  text += "  Static,\n";
  text += "  /// May be followed by a value (ex. `data` in `data-active`).\n";
  text += "  Functional,\n";
  text += "  /// Is followed by another variant (ex. `group` in `group-hover`).\n";
  text += "  Compound,\n";
  text += "}\n\n";
  text += "/// How variants that have the same position are ordered.\n";
  text += "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n";
  text += "pub enum VariantValueOrder {\n";
  text += "  /// By their root then value.\n";
  text += "  None,\n";
  text += "  /// From the smallest value to the largest (ex. the width of the breakpoint in `min-md`).\n";
  text += "  Ascending,\n";
  text += "  /// From the largest value to the smallest (ex. the width of the breakpoint in `max-md`).\n";
  text += "  Descending,\n";
  text += "}\n\n";
  text += "/// Roots of the variants along with their position.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const VARIANTS: &[(&str, VariantKind, u16, VariantValueOrder)] = &[\n${
    variants.roots.map(v =>
      `  (${quote(v.root)}, VariantKind::${v.kind}, ${v.order}, VariantValueOrder::${v.valueOrder}),\n`
    ).join("")
  }];\n\n`;
  text += "/// Variants that are ordered by their value along with that value.\n";
  text += "#[rustfmt::skip]\n";
  text += `pub const VARIANT_VALUES: &[(&str, &str)] = &[\n${
    variants.values.map(([name, value]) => `  (${quote(name)}, ${quote(value)}),\n`).join("")
  }];\n`;
  return text;
}

function getUtilities() {
  const staticNames = new Set<string>(design.utilities.keys("static"));
  const functionalRoots = new Set<string>(design.utilities.keys("functional"));
  const classNames: string[] = design.getClassList()
    .map(([name]: [string]) => name)
    // negative utilities have the position of the positive one
    .filter((name: string) => !name.startsWith("-") && getSortKey(name) != null);
  const classNamesByRoot = new Map<string, string[]>();
  const exact = new Set<string>();
  for (const name of classNames) {
    const root = staticNames.has(name) ? undefined : findRoot(name);
    if (root == null) {
      exact.add(name);
    } else {
      classNamesByRoot.set(root, [...classNamesByRoot.get(root) ?? [], name]);
    }
  }

  const roots = new Map<string, { default: string; arbitraryLength: string; arbitraryColor: string }>();
  for (const root of functionalRoots) {
    // the position of a value that's not known is the most common one of the known values
    const names = classNamesByRoot.get(root) ?? [];
    const counts = new Map<string, { name: string; count: number }>();
    for (const name of names) {
      const key = JSON.stringify(getSortKey(name));
      const entry = counts.get(key) ?? { name, count: 0 };
      entry.count++;
      counts.set(key, entry);
    }
    const arbitraryLength = [`${root}-[1px]`].find(name => getSortKey(name) != null);
    const arbitraryColor = [`${root}-[#000]`].find(name => getSortKey(name) != null);
    const defaultName = Array.from(counts.values()).sort((a, b) => b.count - a.count)[0]?.name
      ?? [arbitraryLength, arbitraryColor, `${root}-[initial]`, `${root}-1`].find(name =>
        name != null && getSortKey(name) != null
      );
    if (defaultName == null) {
      continue;
    }
    roots.set(root, {
      default: defaultName,
      arbitraryLength: arbitraryLength ?? defaultName,
      arbitraryColor: arbitraryColor ?? defaultName,
    });
    const defaultKey = JSON.stringify(getSortKey(defaultName));
    for (const name of names) {
      if (JSON.stringify(getSortKey(name)) !== defaultKey) {
        exact.add(name);
      }
    }
  }
  for (const [root, names] of classNamesByRoot) {
    if (!roots.has(root)) {
      names.forEach(name => exact.add(name));
    }
  }
  return { exact, roots };

  function findRoot(name: string) {
    if (functionalRoots.has(name)) {
      // has no value (ex. `border`), so needs to be matched on its entire text
      return undefined;
    }
    for (let index = name.lastIndexOf("-"); index > 0; index = name.lastIndexOf("-", index - 1)) {
      if (functionalRoots.has(name.substring(0, index))) {
        return name.substring(0, index);
      }
    }
    return undefined;
  }
}

function getSortKey(className: string): SortKey | undefined {
  if (!sortKeys.has(className)) {
    let result: SortKey | undefined;
    for (const candidate of design.parseCandidate(className)) {
      for (const { node, propertySort } of design.compileAstNodes(candidate)) {
        collectProperties(node);
        if (result == null || compareSortKeys(propertySort, result) < 0) {
          result = propertySort;
        }
      }
    }
    sortKeys.set(className, result!);
  }
  return sortKeys.get(className);
}

// deno-lint-ignore no-explicit-any
function collectProperties(node: any) {
  if (node.kind === "declaration") {
    if (!node.property.startsWith("--")) {
      properties.add(node.property);
    }
  } else {
    node.nodes?.forEach(collectProperties);
  }
}

/** Compares the same way as the sort in Tailwind's `compileCandidates`. */
function compareSortKeys(a: SortKey, b: SortKey) {
  let offset = 0;
  while (offset < a.order.length && offset < b.order.length && a.order[offset] === b.order[offset]) {
    offset++;
  }
  return ((a.order[offset] ?? Infinity) - (b.order[offset] ?? Infinity)) || (b.count - a.count);
}

/** Gets the position of each class name's sort key among all the sort keys. */
function getRanks(classNames: string[]) {
  const sorted = Array.from(new Set(classNames)).sort((a, b) => compareSortKeys(getSortKey(a)!, getSortKey(b)!));
  const result = new Map<string, number>();
  let rank = 0;
  for (const [index, className] of sorted.entries()) {
    if (index > 0 && compareSortKeys(getSortKey(sorted[index - 1])!, getSortKey(className)!) !== 0) {
      rank++;
    }
    result.set(className, rank);
  }
  return result;
}

function getVariants() {
  const kinds: Record<string, string> = { static: "Static", functional: "Functional", compound: "Compound" };
  const roots = Array.from<[string, { kind: string; order: number }]>(design.variants.variants.entries())
    .map(([root, { kind, order }]) => ({
      root,
      kind: kinds[kind],
      order,
      // variants that share a position are ordered by their value (ex. the width of a breakpoint)
      valueOrder: !design.variants.compareFns.has(order)
        ? "None"
        : root === "max" || root === "@max"
        ? "Descending"
        : "Ascending",
    }))
    .sort((a, b) => compareText(a.root, b.root));
  const values: [string, string][] = [];
  const valuesByRoot = new Map<string, string[]>(
    design.getVariants().map((v: { name: string; values: string[] }) => [v.name, v.values]),
  );
  for (const { root, kind } of roots.filter(v => v.valueOrder !== "None")) {
    const themeKey = root.startsWith("@") ? "--container" : "--breakpoint";
    if (kind === "Static") {
      values.push([root, design.theme.resolveValue(root, [themeKey])]);
    }
    for (const value of valuesByRoot.get(root) ?? []) {
      values.push([root === "@" ? `@${value}` : `${root}-${value}`, design.theme.resolveValue(value, [themeKey])]);
    }
  }
  if (values.some(([, value]) => value == null)) {
    throw new Error("Expected every breakpoint to have a value.");
  }
  // ensure the directions above are right
  for (
    const [smaller, larger, expected] of [["sm", "min-md", -1], ["max-sm", "max-md", 1], ["@sm", "@min-md", -1], [
      "@max-sm",
      "@max-md",
      1,
    ]] as const
  ) {
    if (Math.sign(design.variants.compare(design.parseVariant(smaller), design.parseVariant(larger))) !== expected) {
      throw new Error(`Unexpected order of ${smaller} and ${larger}.`);
    }
  }
  values.sort((a, b) => compareText(a[0], b[0]));
  return { roots, values };
}

function getSortTestsText() {
  const random = createRandom(1);
  const pick = <T>(items: T[]) => items[Math.floor(random() * items.length)];
  // group the class names so that the many classes for colors don't crowd out the rest
  const classNameGroups = Array.from(
    Map.groupBy(
      design.getClassList().map(([name]: [string]) => name).filter((name: string) => getSortKey(name) != null),
      (name: string) => name.replace(/^-/, "").split("-")[0],
    ).values(),
  ) as string[][];
  const variantNames = [
    ...variants.roots.filter(v => v.kind === "Static").map(v => v.root),
    ...variants.values.map(([name]) => name),
    ...[
      "group-hover",
      "group-focus",
      "peer-checked",
      "peer-hover",
      "not-hover",
      "not-first",
      "has-checked",
      "in-focus",
    ],
    ...["group-hover/item", "peer-checked/name", "group-data-open", "not-data-active"],
    ...["aria-checked", "aria-busy", "data-active", "data-open", "data-[state=open]", "aria-[sort=ascending]"],
    ...[
      "nth-3",
      "nth-last-2",
      "supports-grid",
      "supports-[display:grid]",
      "has-[img]",
      "[&>*]",
      "[&:nth-child(3)]",
      "[@media(width>=600px)]",
    ],
    ...[
      "min-[400px]",
      "max-[600px]",
      "@[300px]",
      "@min-[20rem]",
      "@max-[40rem]",
      "min-[30.5rem]",
      "max-[calc(100%-1rem)]",
      "@sm/sidebar",
    ],
  ];
  const extraClassNames = [
    ...[
      "text-[14px]",
      "text-[#bada55]",
      "bg-[#bada55]",
      "bg-[url(/img.png)]",
      "w-[32rem]",
      "p-[5px]",
      "border-[3px]",
      "border-[#fff]",
    ],
    ...["[color:red]", "[mask-type:alpha]", "[--my-var:1px]", "m-[-2px]", "grid-cols-[1fr_2fr]", "content-['hello']"],
    ...[
      "bg-red-500/50",
      "text-sm/6",
      "text-red-500/[0.5]",
      "border-blue-300/25",
      "w-5/7",
      "-mt-[3px]",
      "text-(--my-color)",
    ],
    ...["!p-4", "p-4!", "!flex", "text-red-500!", "foo", "bar", "unknown-class"],
  ];
  const sizes = [2, 2, 3, 3, 4, 5, 6, 8, 12];
  let text = `# Class lists and how Tailwind CSS ${tailwindVersion} sorts them, separated by \`=>\`.\n`;
  text += "#\n";
  text += "# Generated by scripts/generate_tailwind_tables.ts. Do not edit this file.\n";
  for (let i = 0; i < 1000; i++) {
    const classes = Array.from({ length: pick(sizes) }, () => {
      const className = random() < 0.1 ? pick(extraClassNames) : pick(pick(classNameGroups));
      const variantCount = pick([0, 0, 0, 1, 1, 2, 3]);
      return [...Array.from({ length: variantCount }, () => pick(variantNames)), className].join(":");
    });
    text += `${classes.join(" ")} => ${sortClasses(classes).join(" ")}\n`;
  }
  return text;
}

/** Sorts the same way as prettier-plugin-tailwindcss. */
function sortClasses(classes: string[]) {
  const ordered: [string, bigint | null][] = design.getClassOrder(classes);
  ordered.sort(([, a], [, b]) => {
    if (a === b) return 0;
    if (a === null) return -1;
    if (b === null) return 1;
    return a < b ? -1 : 1;
  });
  const seen = new Set<string>();
  return ordered.filter(([name, order]) => {
    if (seen.has(name)) return false;
    if (order !== null) seen.add(name);
    return true;
  }).map(([name]) => name);
}

/** Creates a seeded random number generator so that the output is reproducible. */
function createRandom(seed: number) {
  return () => {
    seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Compares by UTF-8 bytes like Rust does so that the tables can be binary searched. */
function compareText(a: string, b: string) {
  const encoder = new TextEncoder();
  const aBytes = encoder.encode(a);
  const bBytes = encoder.encode(b);
  for (let i = 0; i < Math.min(aBytes.length, bBytes.length); i++) {
    if (aBytes[i] !== bBytes[i]) {
      return aBytes[i] - bBytes[i];
    }
  }
  return aBytes.length - bBytes.length;
}

function quote(text: string) {
  return JSON.stringify(text);
}
