#!/usr/bin/env -S deno run -A
import { conditions, defineMatrix, expr, job, step, workflow } from "jsr:@david/gagen@^0.5.0";

const pluginName = "typescript";
const cargoWasmName = `dprint_plugin_${pluginName}`;

const matrix = defineMatrix({
  config: [
    { os: "ubuntu-latest", kind: "test_release" },
    { os: "ubuntu-latest", kind: "test_debug" },
  ],
});

const kind = expr("matrix.config.kind");
const os = expr("matrix.config.os");

const isRelease = kind.equals("test_release");
const isDebug = kind.equals("test_debug");
const isTag = conditions.isTag();
const isReleaseAndTag = isRelease.and(isTag);

const getTagVersion = step({
  id: "get_tag_version",
  name: "Get tag version",
  if: isReleaseAndTag,
  run: `echo "TAG_VERSION=\${GITHUB_REF/refs\\/tags\\//}" >> "$GITHUB_OUTPUT"`,
  outputs: ["TAG_VERSION"],
});

const buildJob = job("build", {
  name: `${kind} ${os}`,
  runsOn: os,
  strategy: { matrix },
  env: {
    CARGO_INCREMENTAL: 0,
    RUST_BACKTRACE: "full",
  },
  steps: [
    { uses: "actions/checkout@v6" },
    { uses: "dsherret/rust-toolchain-file@v1" },
    {
      name: "Install wasm32 target",
      if: isRelease,
      run: "rustup target add wasm32-unknown-unknown",
    },
    {
      uses: "Swatinem/rust-cache@v2",
      with: { "save-if": "${{ github.ref == 'refs/heads/main' }}" },
    },
    // deno is needed by the "Lint workflow generation" step (test_debug)
    // and by the "Pre-release" step (test_release on tag). Install it
    // once at the top of every job to keep the matrix steps simple.
    {
      uses: "denoland/setup-deno@v2",
      with: { "deno-version": "v2.x" },
    },

    { name: "Build debug", if: isDebug, run: "cargo build" },
    { name: "Lint", if: isDebug, run: "cargo clippy" },
    { name: "Test debug", if: isDebug, run: "cargo test" },

    {
      name: "Build release",
      if: isRelease,
      run: `cargo build --target wasm32-unknown-unknown --features "wasm" --release`,
    },
    { name: "Test release", if: isRelease, run: "cargo test --release" },

    // wasm integration test (typescript-specific)
    {
      name: "Wasm integration test - Setup",
      if: isRelease,
      run:
        `echo '{ "plugins": ["./target/wasm32-unknown-unknown/release/${cargoWasmName}.wasm"] }' >> dprint.test.json`,
    },
    {
      name: "Wasm integration test - Run",
      if: isRelease,
      uses: "dprint/check@v2.2",
      with: { "config-path": "dprint.test.json" },
    },
    {
      name: "Wasm integration test - Cleanup",
      if: isRelease,
      run: "rm dprint.test.json",
    },

    getTagVersion,

    // NPM
    {
      uses: "actions/setup-node@v6",
      if: isRelease,
      with: {
        "node-version": "24.x",
        "registry-url": "https://registry.npmjs.org",
      },
    },
    {
      name: "Setup and test npm deployment",
      if: isRelease,
      run: [
        "cd deployment/npm",
        "npm install",
        "node setup.js",
        "npm run test",
      ],
    },

    // GITHUB RELEASE
    {
      name: "Pre-release",
      if: isReleaseAndTag,
      run: [
        "# update config schema to have version",
        `sed -i 's/${pluginName}\\/0.0.0/${pluginName}\\/${getTagVersion.outputs.TAG_VERSION}/' deployment/schema.json`,
        "# rename the wasm file",
        `(cd target/wasm32-unknown-unknown/release/ && mv ${cargoWasmName}.wasm plugin.wasm)`,
        "# create release notes",
        `deno run -A ./scripts/generate_release_notes.ts ${getTagVersion.outputs.TAG_VERSION} > \${{ github.workspace }}-CHANGELOG.txt`,
      ],
    },
    {
      name: "Release",
      // pinned because softprops/action-gh-release was once compromised
      uses: "softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844",
      if: isReleaseAndTag,
      env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
      with: {
        files: [
          "target/wasm32-unknown-unknown/release/plugin.wasm",
          "deployment/schema.json",
        ].join("\n"),
        body_path: "${{ github.workspace }}-CHANGELOG.txt",
        draft: false,
      },
    },
    {
      name: "Lint workflow generation",
      if: isDebug,
      run: [
        "./.github/workflows/ci.ts --lint",
        "./.github/workflows/publish.ts --lint",
        "./.github/workflows/release.ts --lint",
      ],
    },
  ],
});

workflow({
  name: "CI",
  on: {
    pull_request: { branches: ["main"] },
    push: { branches: ["main"], tags: ["*"] },
  },
  jobs: [buildJob],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header: "# GENERATED BY ./ci.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
