#!/usr/bin/env -S deno run -A
import { expr, workflow } from "jsr:@david/gagen@^0.5.0";

const releaseKind = expr("github.event.inputs.releaseKind");
const actor = expr("github.actor");

workflow({
  name: "release",
  on: {
    workflow_dispatch: {
      inputs: {
        releaseKind: {
          description: "Kind of release",
          default: "minor",
          type: "choice",
          options: ["patch", "minor"],
          required: true,
        },
      },
    },
  },
  jobs: [{
    id: "rust",
    name: "release",
    runsOn: "ubuntu-latest",
    timeoutMinutes: 30,
    steps: [
      {
        name: "Clone repository",
        uses: "actions/checkout@v6",
        with: { token: "${{ secrets.GH_DPRINTBOT_PAT }}" },
      },
      { uses: "denoland/setup-deno@v2" },
      { uses: "dsherret/rust-toolchain-file@v1" },
      {
        name: "Bump version and tag",
        env: {
          GITHUB_TOKEN: "${{ secrets.GH_DPRINTBOT_PAT }}",
          GH_WORKFLOW_ACTOR: actor,
        },
        run: [
          `git config user.email "${actor}@users.noreply.github.com"`,
          `git config user.name "${actor}"`,
          `deno run -A jsr:@dprint/automation@0.10.3/tasks/publish-release --${releaseKind}`,
        ],
      },
    ],
  }],
}).writeOrLint({
  filePath: new URL("./release.generated.yml", import.meta.url),
  header: "# GENERATED BY ./release.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
